steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', 'github.com/jinzhu/gorm', 'gopkg.in/DATA-DOG/go-sqlmock.v1', 'github.com/gorilla/mux', 'github.com/urfave/negroni', 'github.com/lib/pq']
  env: ['GOPATH=/gopath', 'PROJECT_ROOT=.']
  volumes:
  - name: 'go'
    path: '/gopath'
- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-d', './...']
  env: ['GOPATH=/gopath', 'PROJECT_ROOT=.']
  volumes:
  - name: 'go'
    path: '/gopath'
- name: 'gcr.io/cloud-builders/go'
  args: ['test', './...']
  env: ['GOPATH=/gopath', 'PROJECT_ROOT=.']
  volumes:
  - name: 'go'
    path: '/gopath'
- name: 'gcr.io/cloud-builders/go'
  args: ['test', './...', '-cover']
  env: ['GOPATH=/gopath', 'PROJECT_ROOT=.']
  volumes:
  - name: 'go'
    path: '/gopath'
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-i', '-o', './bin/appdocker']
  env: ['GOPATH=/gopath', 'PROJECT_ROOT=.']
  volumes:
  - name: 'go'
    path: '/gopath'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - deployment/poc-app
  - poc-app=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=your-first-cluster-1'
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']