version: '3'
services:
    db:
        build:
            context: ./docker/db
        environment:
            - POSTGRES_PASSWORD=secret
            - POSTGRES_USER=postgres
        container_name: postgres
        ports:
           - "5432:5432"
        networks:
            - cloud-builder
    app:
        image: app:latest
        ports:
            - "8080:8080"
        container_name: cloud-builder-poc
        depends_on:
            - db
        networks:
            - cloud-builder
        environment:
            - DEPLOY_ENV=local
            - POSTGRES_PASSWORD=secret
            - POSTGRES_USER=postgres
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_DBNAME=web

networks:
    cloud-builder:
        driver: bridge